# Generated by Django 3.0.7 on 2020-07-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FailedGameUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_log", models.FileField(upload_to="")),
                ("notes", models.TextField()),
            ],
        ),
    ]
