# Generated by Django 3.0.7 on 2020-07-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_auto_20200720_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failedgameupload",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
