# Generated by Django 3.2.4 on 2021-08-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_failedgameupload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedgameupload',
            name='game_log',
            field=models.JSONField(),
        ),
    ]
