# Generated by Django 2.2.3 on 2019-08-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("games", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="playerstat",
            old_name="average_chug_time",
            new_name="average_chug_time_seconds",
        )
    ]
