# Generated by Django 2.2.3 on 2019-08-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0002_auto_20190803_2241")]

    operations = [
        migrations.AlterField(
            model_name="card", name="drawn_datetime", field=models.DateTimeField()
        )
    ]
