# Generated by Django 2.2.3 on 2019-07-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("games", "0002_auto_20190707_0053")]

    operations = [migrations.AlterModelOptions(name="game", options={})]
