# Generated by Django 2.2.4 on 2019-08-11 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("games", "0003_auto_20190809_2339")]

    operations = [migrations.RemoveField(model_name="user", name="old_password_hash")]
