# Generated by Django 2.2.3 on 2019-07-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190707_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-end_datetime',)},
        ),
    ]
