# Generated by Django 2.2.3 on 2019-08-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0005_auto_20190707_0131")]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ("username",)}),
        migrations.AlterField(
            model_name="card",
            name="value",
            field=models.SmallIntegerField(
                choices=[
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "Jack"),
                    (12, "Queen"),
                    (13, "King"),
                    (14, "Ace"),
                ]
            ),
        ),
    ]
