# Generated by Django 2.2.4 on 2019-08-12 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("games", "0005_auto_20190811_2104")]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        )
    ]
