# Generated by Django 2.2.3 on 2019-08-03 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190802_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('total_games', models.PositiveIntegerField()),
                ('total_time_played', models.FloatField()),
                ('total_sips', models.PositiveIntegerField()),
                ('best_game_sips', models.PositiveIntegerField(null=True)),
                ('worst_game_sips', models.PositiveIntegerField(null=True)),
                ('total_chugs', models.PositiveIntegerField()),
                ('average_chug_time', models.FloatField(null=True)),
                ('best_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Game')),
                ('fastest_chug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Chug')),
                ('fastest_chug_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worst_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Game')),
            ],
        ),
    ]
