# Generated by Django 2.2.3 on 2019-08-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_playerstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='fastest_chug_game',
        ),
    ]
