# Generated by Django 2.2.3 on 2019-08-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("games", "0008_remove_playerstat_fastest_chug_game")]

    operations = [
        migrations.RenameField(
            model_name="playerstat",
            old_name="total_time_played",
            new_name="total_time_played_seconds",
        )
    ]
