# Generated by Django 2.2.3 on 2019-08-03 19:58

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [("games", "0009_auto_20190803_0417")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=games.models.DeterministicFileSystemStorage(),
                upload_to=games.models.get_user_image_path,
            ),
        )
    ]
