# Generated by Django 2.2.8 on 2020-02-18 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_gameplayerstat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameplayerstat",
            old_name="aces",
            new_name="chugs",
        ),
    ]
