# Generated by Django 3.0.4 on 2020-04-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_auto_20200419_1649"),
        ("games", "0009_auto_20200215_2321"),
    ]

    operations = []
