# Generated by Django 3.0.4 on 2020-04-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_auto_20200422_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="games.Game"
                    ),
                ),
            ],
        ),
    ]
