# Generated by Django 3.0.5 on 2020-04-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0015_onetimepassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
