# Generated by Django 3.0.8 on 2020-08-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0016_auto_20200423_0534"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="location_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="location_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="location_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
