# Generated by Django 3.0.8 on 2020-10-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0019_auto_20200912_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="facebook_post_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
