# Generated by Django 3.1.2 on 2020-10-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0020_game_facebook_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
