# Generated by Django 3.1.2 on 2020-10-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0022_game_shuffle_indices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ("dnf", "-end_datetime")},
        ),
    ]
