# Generated by Django 5.2.1 on 2025-05-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0025_auto_20210420_2222"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="dnf_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
