# Generated by Django 5.2.1 on 2025-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0026_gameplayer_dnf_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstat",
            name="total_games_with_game_dnf",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstat",
            name="total_games_with_player_and_game_dnf",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstat",
            name="total_games_with_player_dnf",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
